### ISSUE TITLE
Database Scehma is incompatible with Sqlboiler

### ISSUE THREAD

**Issue by josdotso** [datacharmer/test_db#19]
I see errors like, "type DeptEmp has both field and method named EmpNo" when running this schema through sqlboiler (https://github.com/volatiletech/sqlboiler) and it seems like a legitimate concern beyond Go and sqlboiler.

See: https://github.com/volatiletech/sqlboiler/issues/341#issuecomment-405119154

Thoughts?

**Comment by datacharmer** [comment]
I don't know sqlboiler, and the error seems a software glitch rather than a schema inconsistency.
I may look into it, but I need to know how to reproduce the problem to see whether it's a test_db problem or something else.

Please show the detailed steps to reproduce the issue including:
* which executable, taken from where, and compiled with which command,
* which command was run with the executable and configuration files used.
* expected result.

Possibly, run the tool against [some other known sample database](https://dev.mysql.com/doc/index-other.html) and see if it does what you expect.
